# Common configuration for all services
management:
  endpoints:
    web:
      exposure:
        include: health,info
        
logging:
  level:
    com.quizwars: DEBUG
    
server:
  servlet:
    context-path: /
